### ISSUE TITLE
Post button gets permaently disabled if some fields are left empty

### ISSUE THREAD

**Issue by AbhyasKanaujia** [kumarsks619/u-store-first-prototype#1]
## Steps to Reproduce

1. Click "Want to sell something?" on homepage
2. Fill the form that appears but leave at least one field blank
3. Click Post; Error shows "`missed field` is needed"
4. Provide data in all fields

## Expected Behavior

At this point the `Post` button should have been re-enabled since the user have provided all the fields.

## Current Behavior

The `Post` buttons remains disabled.

**Comment by kumarsks619** [comment]
Thanks for raising the issue.
Actually, I wanted to know that how did you browse my website/project in order to discover this issue?

**Comment by kumarsks619** [comment]
Thanks @AbhyasKanaujia 
The bug has been fixed and deployed to production.
But for your info this is not the repo of that U-store, the website on which you spotted the bug is another repo called "U-store".
The current repo on which you just raised the bug is the very first prototype of my idea.
Anyways thanks a lot!
Keep hunting bugs!!!!
